version: '3.9'

services:
  postgres:
    image: postgres:17.6
    container_name: ai-crash-course-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_crash_course
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:8.0.13
    container_name: ai-crash-course-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata:


